### ISSUE TITLE
Mudanca de Tag

### ISSUE THREAD

**Issue by AdelvaneFerreira** [lucasfpds/repoExerCubosAcademy#5]
https://github.com/lucasfpds/repoExerCubosAcademy/blob/master/1%C2%BA%20M%C3%B3dulo/04_front-integral-mais-elementos/classe-01/index.html

Nesse arquivo html a segunda seção poderia ser feita com uma lista ordenada.

**Comment by lucasfpds** [comment]
Alteração feita.
